apiVersion: v1
kind: Service
metadata:
  name: azure-cognitive-service-layout
  namespace: form-recognizer
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: layout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: layout
  namespace: form-recognizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: layout
  template:
    metadata:
      labels:
        app: layout
    spec:
      containers:
        - name: azure-cognitive-service-layout
          image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/layout-3.0:latest
          env:
            - name: "EULA"
              value: "accept"
            - name: "billing"
              value: "-replace with your cognitive services endpoint-"
            - name: "apikey"
              valueFrom:
                secretKeyRef:
                  name: service-credentials
                  key: formrecognizer-apikey
            - name: "ApplicationInsights__InstrumentationKey"
              valueFrom:
                secretKeyRef:
                  name: service-credentials
                  key: appinsights-instrumentationkey
            - name: "Logging__Console__LogLevel__Default"
              value: "Information"
            - name: "Logging__Disk__LogLevel__Default"
              value: "Information"              
            - name: "Logging__Disk__Format" 
              value: "json"
            - name: "SharedRootFolder" 
              value: "/shared"
            - name: "Mounts__Shared" 
              value: "/shared"
            - name: "Mounts__Output"
              value: "/logs"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: shared
              mountPath: "/shared"
            - name: output
              mountPath: "/logs"
          resources:
            limits:
              cpu: "8"
              memory: "16Gi"
            requests:
              cpu: "4"
              memory: "8Gi"    
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared
        - name: output
          persistentVolumeClaim:
            claimName: output
