apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  namespace: form-recognizer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: reverseproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: form-recognizer
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      containers:
      - name: reverseproxy
        image: nginx:alpine
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          #runAsUser: 0
        volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx
              #subPath: nginx.conf
              readOnly: true
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
